[package]
name = "stylus-erc20"
version = "0.1.0"
edition = "2021"

[dependencies]
stylus-sdk = "0.9.0"
mini-alloc = "0.6.0"
alloy-primitives = "=0.8.20"
alloy-sol-types = "=0.8.20"

[features]
export-abi = ["stylus-sdk/export-abi"]

[lib]
crate-type = ["lib", "cdylib"]

[[bin]]
name = "stylus-erc20"
path = "src/main.rs"
required-features = ["export-abi"]

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = "s"